language: node_js,
node_js:
- "8.11"

branches: 
  only:
    - master

addons:
  chrome: stable

before_script: 
  - yarn global add @angular/cli
  - cd ProjectManagerClient

cache:
  yarn: true,
  directories:
    - node_modules

script:
  - npm install
  - ng build